### ISSUE TITLE
Layer image stack

### ISSUE THREAD

**Issue by sacy80** [keyz182/SparkTimer#1]
hahahah . i will be your first tester.. 

i found that the app dont clear the first files. it still show the fist layer preview of the first loaded file. when i drag another file in, the layer preview will have both first loaded and 2nd loaded img.  :)

**Comment by keyz182** [comment]
Good catch, should be fixed now in [V1.2.0](https://github.com/keyz182/SparkTimer/releases/tag/V1.2.0)
